### ISSUE TITLE
Can I integrate a Twitter Icon in the nav links

### ISSUE THREAD

**Issue by andy4thehuynh** [lucaslew/whitespace#70]
I set my `twitter user`in _config.yml. Was curious if I can render a Twitter icon where my github icon lives [here](andy4thehuynh.github.io)

**Comment by lerrua** [comment]
+1

**Comment by TheChymera** [comment]
Hi there, your link seems broke. What is the issue again?is the twitter icon not working?

**Comment by lerrua** [comment]
@TheChymera this is the link http://andy4thehuynh.github.io

The issue is about the `twitter_user` in _config.yml doesn't work yet.

**Comment by TheChymera** [comment]
https://github.com/lucaslew/whitespace/blob/master/source/_includes/navigation.html

This is where we keep our (inline) SVG icons. AFAICT the reason twitter does not work is that we do not have an icon. I'll put this on my to-do list; but I am very busy this week.

You can expedite the process by linking me to a good SVG monochrome twitter logo, or adding the SVG xml to the file in a pull request.
