### ISSUE TITLE
Target blank for external links

### ISSUE THREAD

**Issue by bandrzejczak** [lucaslew/whitespace#73]
What do you thing of external links being opened in another tab? I mean links like github, bitbucket, google+ and alike.

**Comment by TheChymera** [comment]
Could you please rephrase? Generally we wouldn't want to send visitors away from our sites, so unless they explicitly want to close our tab, we would rather keep it opened.

**Comment by bandrzejczak** [comment]
It's the case here. I want to keep the user on my website, while if you click one of the social icons, it will open in the current tab and close my website. By adding target="_blank" to the links, it would make them open in a new tab, preserving opened website.

**Comment by TheChymera** [comment]
If you can make a patch for that, I would be happy to pull it!

**Comment by bandrzejczak** [comment]
I'll make a patch this week.
