### ISSUE TITLE
My demo site is no longer available

### ISSUE THREAD

**Issue by yous** [lucaslew/whitespace#74]
http://yous.be

I decided to use Jekyll directly, created a different theme from the default one of Jekyll.

**Comment by TheChymera** [comment]
Does this mean you'll also suspend your efforts on whitespace? I was actually thinking of moving the whitespace (name and concept, if not the code) to octopress3 as soon as it come out. As I understand octopress3 will just be a collection of tools for jeckyll (no idea how themes will be managed, though - perhaps we can make a whitespace theme for jeckyll?).

**Comment by yous** [comment]
If Octopress 3 is just a collection of tools for Jekyll, as you said, then we can make a whitespace for Jekyll. I think the default theme of Octopress has quite complex `source/_includes` and `sass` directory. This makes user hard to find where to edit, hard to change some CSS they want. If we have to rewrite a whitespace, I want to refactor the file structure first. Maybe we can keep our eyes to the default theme of Octopress 3.

**Comment by TheChymera** [comment]
:+1:

**Comment by yous** [comment]
Since the blog reference is removed from the Demos section in README.md, so closing this.
