### ISSUE TITLE
Stackoverflow and LinkedIn icon

### ISSUE THREAD

**Issue by bandrzejczak** [lucaslew/whitespace#75]
I've implemented stackoverflow and linked icons on the navigation bars, that work based on data contained in `_config.yml` file. Should I create a pull request for it?

Stack's icon is show [on my website](http://bandrzejczak.com/), while linkedin icon was shown, but then I left it behind. You can see my implementation [here](https://github.com/bandrzejczak/bandrzejczak.github.io/blob/source/source/_includes/navigation.html#L61-L122).

There are also some changes in styles (icons are color-filled on hover), but I guess it could be a subject of yet another pull request. Of course if you agree on adding some colors to "whitespace". I liked it, so I've got it on my website, but it doesn't mean automatic pull request ;)

**Comment by TheChymera** [comment]
I'm definitely interested in pulling more profile icons. As for the coloring, while I do agree that it looks ok on your website, for now, I would rather keep the hover effect grayscale.
