### ISSUE TITLE
Table style

### ISSUE THREAD

**Issue by bandrzejczak** [lucaslew/whitespace#78]
I've recently found out, that there is absolutely no style for table, even though Octopress can handle them. I've copied a style from github, which here looks like this:

| Header1 | Header2 |
|:-----------:|:-------------|
| centered | left          |
|another one| end      |

I've used it in this post: [http://bandrzejczak.com/blog/2015/02/15/the-cost-of-the-garbage-collection/](http://bandrzejczak.com/blog/2015/02/15/the-cost-of-the-garbage-collection/)

Do you want me to create a pull request?

**Comment by TheChymera** [comment]
looks good enought ;) Are you by any chance using octopress3 already? We're thinking about how we could best port our theme to it when it comes out in force ^^

**Comment by bandrzejczak** [comment]
I'll create PR later today. I'm still not using octopress3. I'm waiting for a stable release. I'm happy with version 2 for now ;)
