### ISSUE TITLE
Linkedin integration not showing up

### ISSUE THREAD

**Issue by mkhsueh** [lucaslew/whitespace#81]
Hi Lucas, great work on this theme! I tried adding the Linkedin integration in _config.yml the following ways:

linkedin_user: publicProfileId 
linkedin_user: actualLinkUrl

However, nothing new seems to appear. Perhaps I'm going about this the wrong way. Any help would be appreciated!

Thanks,
Michael

**Comment by sarangbaheti** [comment]
@mkhsueh: I did add linkedin support on my blog (http://www.nullptr.me).
My linked public url is: https://www.linkedin.com/in/sarangbaheti
and the id i entered in _config.yml is sarangbaheti

**Comment by mkhsueh** [comment]
@sarangbaheti , thanks for your response! I ended up doing a fresh rake install for whitespace (no additional config changes), and the Linkedin integration worked. Perhaps I was using an older version that didn't have that support yet.
